In [6]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.linalg

In [7]:
A =  np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [11]:
L = np.array([[1, 0, 0], [0.25, 1, 0], [0.5, -0.4, 1]])
U = np.array([[4, 28, 73], [0, -5, -15.25], [0, 0, -21.6]])
A = np.dot(L, U)
P, L, U = scipy.linalg.lu(A)
print(A)
B = np.array([4, 1, 3])
np.linalg.solve(A, B)

[[ 4. 28. 73.]
 [ 1.  2.  3.]
 [ 2. 16. 21.]]


array([ 0.85648148,  0.1412037 , -0.0462963 ])